name: Deploy to Azure

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Replace with your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build # Adjust this to your build command

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: <your-app-service-name>  # Replace with your Azure App Service name
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

